## The suite registry. Every ported test file is a module here, exporting
## `run(t: var T)`, and is named exactly as its .sh predecessor was so the
## verdict lines and the goldens under tests/golden/ keep their paths.
##
## GENERATED by tests/suites/regen.py — add a tests/suites/<name>.nim with a
## `run*` proc and re-run it. The registry is bookkeeping, not a decision.

import ../harness
import actor_result
import auto_alias
import bare_variant
import cli_smoke
import complexity
import declarations
import diagnostics
import duplicates
import end_to_end
import examples
import extern_impl
import frontend
import fuzz_corpus
import interface_call
import interface_dispatch
import interface_seq
import interface_wrap
import interfaces
import known_bugs
import loop_var_type
import mangle
import member_names
import object_composition
import odin_backend
import optimize
import pointer_containment
import typecheck
import uninit
import value_semantics
import when_target

type Entry = tuple[name: string, body: SuiteProc, quick: bool]

# `quick` marks the check-only suites — no `tuck build`, no `odin build`. Those
# are what tests/run --quick runs, the inner-loop gate that quick-test.sh was.
let registry: seq[Entry] = @[
  ("actor_result",        SuiteProc(actor_result.run),        true),
  ("auto_alias",          SuiteProc(auto_alias.run),          false),
  ("bare_variant",        SuiteProc(bare_variant.run),        true),
  ("cli_smoke",           SuiteProc(cli_smoke.run),           false),
  ("complexity",          SuiteProc(complexity.run),          true),
  ("declarations",        SuiteProc(declarations.run),        false),
  ("diagnostics",         SuiteProc(diagnostics.run),         false),
  ("duplicates",          SuiteProc(duplicates.run),          true),
  ("end_to_end",          SuiteProc(end_to_end.run),          false),
  ("examples",            SuiteProc(examples.run),            true),
  ("extern_impl",         SuiteProc(extern_impl.run),         false),
  ("frontend",            SuiteProc(frontend.run),            true),
  ("fuzz_corpus",         SuiteProc(fuzz_corpus.run),         true),
  ("interface_call",      SuiteProc(interface_call.run),      true),
  ("interface_dispatch",  SuiteProc(interface_dispatch.run),  false),
  ("interface_seq",       SuiteProc(interface_seq.run),       false),
  ("interface_wrap",      SuiteProc(interface_wrap.run),      true),
  ("interfaces",          SuiteProc(interfaces.run),          true),
  ("known_bugs",          SuiteProc(known_bugs.run),          false),
  ("loop_var_type",       SuiteProc(loop_var_type.run),       false),
  ("mangle",              SuiteProc(mangle.run),              true),
  ("member_names",        SuiteProc(member_names.run),        true),
  ("object_composition",  SuiteProc(object_composition.run),  false),
  ("odin_backend",        SuiteProc(odin_backend.run),        false),
  ("optimize",            SuiteProc(optimize.run),            false),
  ("pointer_containment", SuiteProc(pointer_containment.run), true),
  ("typecheck",           SuiteProc(typecheck.run),           true),
  ("uninit",              SuiteProc(uninit.run),              false),
  ("value_semantics",     SuiteProc(value_semantics.run),     false),
  ("when_target",         SuiteProc(when_target.run),         false),
]

proc suiteBody*(name: string): SuiteProc =
  for e in registry:
    if e.name == name: return e.body
  raise newException(ValueError, "no such suite: " & name)

proc allSuites*(): seq[string] =
  for e in registry: result.add e.name

proc quickSuites*(): seq[string] =
  for e in registry:
    if e.quick: result.add e.name
