## The suite registry. Every ported test file is a module here, exporting
## `run(t: var T)`, and is named exactly as its .sh predecessor was so the
## verdict lines and the goldens under tests/golden/ keep their paths.
##
## GENERATED by tests/suites/regen.py — add a tests/suites/<name>.nim with a
## `run*` proc and re-run it. The registry is bookkeeping, not a decision.

import ../harness
import actor_result
import auto_alias
import bare_variant
import interface_call
import interface_wrap
import interfaces
import loop_var_type
import mangle
import member_names

type Entry = tuple[name: string, body: SuiteProc, quick: bool]

# `quick` marks the check-only suites — no `tuck build`, no `odin build`. Those
# are what tests/run --quick runs, the inner-loop gate that quick-test.sh was.
let registry: seq[Entry] = @[
  ("actor_result",   SuiteProc(actor_result.run),   true),
  ("auto_alias",     SuiteProc(auto_alias.run),     false),
  ("bare_variant",   SuiteProc(bare_variant.run),   true),
  ("interface_call", SuiteProc(interface_call.run), true),
  ("interface_wrap", SuiteProc(interface_wrap.run), true),
  ("interfaces",     SuiteProc(interfaces.run),     true),
  ("loop_var_type",  SuiteProc(loop_var_type.run),  false),
  ("mangle",         SuiteProc(mangle.run),         true),
  ("member_names",   SuiteProc(member_names.run),   true),
]

proc suiteBody*(name: string): SuiteProc =
  for e in registry:
    if e.name == name: return e.body
  raise newException(ValueError, "no such suite: " & name)

proc allSuites*(): seq[string] =
  for e in registry: result.add e.name

proc quickSuites*(): seq[string] =
  for e in registry:
    if e.quick: result.add e.name
