## benches/containers, held to what its ledger says (benches/SCORES.md,
## "Container copying").
##
## The bench itself is timed by hand, so nothing ran it between 2026-09-11 and
## 2026-10-04, and it rotted three ways unseen:
##   * two patterns stopped building on every backend — they wrote a call in a
##     payload, which TK-PA13 refused after they were written;
##   * generic_box segfaulted on Odin (a generic record's Seq field was
##     invisible to the escape analysis);
##   * four patterns went quadratic on Nim — a parameter read through a field
##     lost its `sink` when the SSA mirror took over the last-use stamps.
##
## A timing cannot run here, but every one of those has a cheap witness: the
## pattern must CHECK, and the Nim `sink` that makes a threaded container
## linear must be in the emitted signature (and absent where the fn only
## reads). The patterns are generated by the bench's own gen.sh, so this tests
## the bench as it is, not a copy of it. The Odin segfault is guarded in
## known_bugs ("a generic record returned with a moved Seq keeps it").
import std/[os, osproc]
import ../harness

const patterns = ["seq_push", "rec_thread", "chain_form", "generic_box",
                  "two_fields", "str_concat", "str_builder", "seq_setat",
                  "read_only"]

proc generated(t: T): string =
  ## Where gen.sh writes its patterns for this run.
  t.dir / "gen"

proc patternSrc(t: T, p: string): string =
  ## One pattern's source, as the bench generates it; "" in the report pass,
  ## when `src` only counts.
  if t.phase == pCollect: readFile(t.generated / p / "b.tuck") else: ""

proc run*(t: var T) =
  ## Registers the container bench's witnesses: every pattern checks, and
  ## Nim's `sink` sits where the ledger needs it.
  if t.phase == pCollect:
    let (outp, rc) = execCmdEx("bash " & t.root / "benches/containers/gen.sh" &
                               " 100 " & t.generated)
    doAssert rc == 0, "benches/containers/gen.sh failed: " & outp

  for p in patterns:
    t.src t.patternSrc(p)
    t.okCheck p & " checks"
    case p
    of "rec_thread", "chain_form":
      t.emits "...and threads its Bag through a sink",
              r"proc tuckˑfnˑaddTo\*\(b: sink tuckˑtypeˑBag"
    of "generic_box":
      t.emits "...and threads its Box[T] through a sink",
              r"proc tuckˑfnˑadd\*\[T\]\(b: sink tuckˑtypeˑBox\[T\]"
    of "two_fields":
      t.emits "...and threads its Pair through a sink",
              r"proc tuckˑfnˑput\*\(p: sink tuckˑtypeˑPair"
    of "str_builder":
      t.emits "...and threads its Builder through a sink",
              r"proc tuckˑfnˑadd\*\(b: sink tuckˑtypeˑBuilder"
    of "seq_setat":
      t.emits "...and threads its Bag through a sink",
              r"proc tuckˑfnˑbump\*\(b: sink tuckˑtypeˑBag"
    of "read_only":
      t.emits "...and only borrows the Bag it reads",
              r"proc tuckˑfnˑtotal\*\(b: tuckˑtypeˑBag\)"
    else: discard

  t.finish()
