#!/usr/bin/env python3
"""Regenerate tests/suites/all.nim from the .nim files sitting beside it.

The registry is pure bookkeeping — one import and one row per suite — so it is
derived rather than hand-edited. QUICK lists the check-only suites: no
`tuck build`, no `odin build`, which is what `tests/run --quick` runs and what
quick-test.sh used to.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# The check-only suites, from quick-test.sh's list. Everything else needs a
# build or an odin, so it stays out of the inner-loop gate.
QUICK = {
    "typecheck", "frontend", "examples", "pointer_containment", "interfaces",
    "interface_wrap", "interface_call", "actor_result", "bare_variant",
    "member_names", "mangle", "complexity", "duplicates", "fuzz_corpus",
    "syntax_ceilings", "fn_size",
}

# Not suites: the registry itself, and helper modules that export no `run`.
NOT_SUITES = {"all", "smokelib"}

names = sorted(
    f[:-4] for f in os.listdir(HERE)
    if f.endswith(".nim") and f[:-4] not in NOT_SUITES
)

w = max(len(n) for n in names) + 2
rows = "\n".join(
    '  ("{}",{} SuiteProc({}.run),{} {}),'.format(
        n, " " * (w - len(n) - 2), n, " " * (w - len(n) - 2),
        "true" if n in QUICK else "false")
    for n in names
)
imports = "\n".join("import " + n for n in names)

open(os.path.join(HERE, "all.nim"), "w").write(f'''\
## The suite registry. Every ported test file is a module here, exporting
## `run(t: var T)`, and is named exactly as its .sh predecessor was so the
## verdict lines and the goldens under tests/golden/ keep their paths.
##
## GENERATED by tests/suites/regen.py — add a tests/suites/<name>.nim with a
## `run*` proc and re-run it. The registry is bookkeeping, not a decision.

import ../harness
{imports}

type Entry = tuple[name: string, body: SuiteProc, quick: bool]

# `quick` marks the check-only suites — no `tuck build`, no `odin build`. Those
# are what tests/run --quick runs, the inner-loop gate that quick-test.sh was.
let registry: seq[Entry] = @[
{rows}
]

proc suiteBody*(name: string): SuiteProc =
  for e in registry:
    if e.name == name: return e.body
  raise newException(ValueError, "no such suite: " & name)

proc allSuites*(): seq[string] =
  for e in registry: result.add e.name

proc quickSuites*(): seq[string] =
  for e in registry:
    if e.quick: result.add e.name
''')
print(f"registered {len(names)} suites")
